# Generated by Django 5.0.6 on 2024-06-28 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_accountpasswordresetprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accountpasswordresetprofile',
            name='reset_password_token',
        ),
        migrations.AddField(
            model_name='accountpasswordresetprofile',
            name='reset_password_otp',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
